---
deployment:
  tasks:
    - export DEPLOYPATH=/home/y9uwzpy6qfx0/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp beams.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp custom.html $DEPLOYPATH
    - /bin/cp gallery.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
